kind: pipeline
type: docker
name: test and build
steps:
  - name: test
    image: docker.io/golang:1.18-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base git
      - go install mvdan.cc/garble@c9337022a0ee9d5e2135a49a49d9ddc593618bb9
      - cd wraith
      - go version
      #- go test -v ./...
      - garble version
      - garble -literals -tiny -seed=random test -v ./...
  - name: build
    image: docker.io/golang:1.18-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base git
      - go install mvdan.cc/garble@c9337022a0ee9d5e2135a49a49d9ddc593618bb9
      - cd wraith
      - go version
      #- go build -v -trimpath .
      - garble version
      - garble -literals -tiny -seed=random build -v -trimpath .
