kind: pipeline
type: docker
name: test and build
steps:
  - name: build
    image: docker.io/golang:1.17-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base
      - cd wraith
      - go build -v -trimpath .
      - go version