kind: pipeline
type: docker
name: test and build
steps:
  - name: test
    image: docker.io/golang:1.18-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base git
      - go install mvdan.cc/garble@79b6e4db3dae31b9f37eeef0f150111a9f262126
      - cd wraith
      - go version
      #- go test -v ./...
      - garble version
      - garble -literals -tiny -seed=random test -v ./...
  - name: build
    image: docker.io/golang:1.18-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base git
      - go install mvdan.cc/garble@79b6e4db3dae31b9f37eeef0f150111a9f262126
      - cd wraith
      - go version
      #- go build -v -trimpath .
      - garble version
      - garble -literals -tiny -seed=random build -v -trimpath .
