kind: pipeline
type: docker
name: code quality and build
steps:
  - name: lint
    image: golangci/golangci-lint
    depends_on: [ clone ]
    commands:
      - cd wraith
      - golangci-lint run -v
  - name: build
    image: docker.io/golang:1.16-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base
      - cd wraith
      - go build -v -trimpath .