kind: pipeline
type: docker
name: test
steps:
  - name: test
    image: docker.io/golang:1.20-alpine
    depends_on: [ clone ]
    commands:
      - apk add --no-cache build-base git
      - go install mvdan.cc/garble@4d7546703a0df7d2b9133b319ae62369f98458e8
      - cd wraith
      - go version
      - garble version
      - garble -literals -tiny -seed=random test -v ./...
